### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by Lusitaniae** [SchizoDuckie/PimpMyuTorrent#1]
Using Win7, updated Chrome and utorrent 3.4.2 35702 32 bit

I click on your website but nothing happens

**Comment by Lusitaniae** [comment]
Using the window from DuckieTv app works however

**Comment by SchizoDuckie** [comment]
Could you refresh the page, enable the debug toolbar in chrome (hit F12) and then refresh the page and click the pimp button again? 

Please hit print-screen after that, and paste it here in the ticket :)

**Comment by Lusitaniae** [comment]
Here you go
  GET https://localhost:10000/version/?callback=angular.callbacks._0 net::ERR_INSECURE_RESPONSE

![image](https://cloud.githubusercontent.com/assets/58325/6220196/5c314420-b62b-11e4-8dd8-b0d7e79d2b35.png)

**Comment by SchizoDuckie** [comment]
Hmm aha.

Do you have something like HTTPS anywhere enabled by accident? The api only listens on HTTP, it shouldn't even try to access it on https.

**Comment by Lusitaniae** [comment]
No, 
I have these active, which shouldn't have any effect:

Autocomplete = on 1.0
History Limiter 1.0.5
Magic Actions for YouTube™ 6.8.4.1  
PerfectPixel by WellDoneCode 1.71
Send to Kindle for Google Chrome™ 1.0.1.56

Anyway, if it's just me I've accessed it through Duckie Tv and it's done

**Comment by SchizoDuckie** [comment]
Yeah i'm going to hold it on some local configuration thingie, maybe a firewall or antivirus engine that's installed?

The line that determines the endpoint for connecting is here. http is hardcoded in it, so why it connects to https for you is a complete mystery to me.
https://github.com/SchizoDuckie/PimpMyuTorrent/blob/gh-pages/js/duckietorrent.torrent.js#L36
