### ISSUE TITLE
Offline version?

### ISSUE THREAD

**Issue by p1r473** [SchizoDuckie/PimpMyuTorrent#13]
Can you create a downloadable offline version?

**Comment by SchizoDuckie** [comment]
you can try "save webpage as" in the menu and see if that works. other than that, nope sorry.

**Comment by SchizoDuckie** [comment]
I really don't see the use case by the way. something offline for a torrent client that requires an Internet connection as well???

**Comment by p1r473** [comment]
I just don't like relying on websites that might not be around forever

**Comment by SeaHOH** [comment]
Go #19 to have a try.
