### ISSUE TITLE
3.4.2

### ISSUE THREAD

**Issue by grumblerbear** [SchizoDuckie/PimpMyuTorrent#3]
Don't work with 3.4.2 version

**Comment by SchizoDuckie** [comment]
Please elaborate :) Can you specify the build? Have you completely shutdown and restarted utorrent? Are  you running any chrome extensions?

**Comment by grumblerbear** [comment]
build 38912, yes, run in clear firefox

**Comment by SchizoDuckie** [comment]
Could you press F12 for me (opening up the inspector), switch to the
console tab and show me the debug output? Please reload the page before
doing this and then press the pimp button again (you can hit print-screen
and just paste right here)

**Comment by garfield69** [comment]
@SchizoDuckie does pimpMyuTorrent run on FireFox?

**Comment by SchizoDuckie** [comment]
@garfield69  yeap without any problems on build 38913 here:
![image](https://cloud.githubusercontent.com/assets/111710/6607516/bf77ecac-c83f-11e4-9856-402b54e95024.png)

**Comment by grumblerbear** [comment]
"error fetching" "version" duckietorrent.torrent.js:98:20
"Could not connect to one of the ports!" duckietorrent.torrent.js:273:24
this.$get/methods.Scan/<() duckietorrent.torrent.js:273
qFactory/defer/deferred.promise.then/wrappedErrback() angular.min.js:11042
qFactory/createInternalRejectedPromise/<.then/<() angular.min.js:11174
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.min.js:12045
$RootScopeProvider/this.$get</Scope.prototype.$digest() angular.min.js:11871
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.min.js:12151
done() angular.min.js:7909
completeRequest() angular.min.js:8110
createHttpBackend/</jsonpDone<() angular.min.js:8015
jsonpReq/doneWrapper() angular.min.js:8123
jsonpReq/script.onerror() angular.min.js:8137

**Comment by SchizoDuckie** [comment]
It looks like either utorrent is not running or you have a firewall that prevents firefox from connecting to uTorrent. Can you check that? The JSON API is enabled by default otherwise. There's just nothing listening to any of the 20 ports the portscan is trying to connect to.

**Comment by grumblerbear** [comment]
Don't work in clear IE and FF, but work in clear Chrome

**Comment by SchizoDuckie** [comment]
Sorry, it must be a problem with your system being configured to reject these connections somehow. Analytics says that there are 3500 people who've successfully pimped their utorrent using Firefox to date. 

I'm going to close this issue, glad you at least got it to work in chrome :+1:

**Comment by grumblerbear** [comment]
thanks!
