### ISSUE TITLE
JS code

### ISSUE THREAD

**Issue by stdedos** [SchizoDuckie/PimpMyuTorrent#4]
Where can we see the JS code run?

**Comment by SchizoDuckie** [comment]
Can you elaborate? What do you mean?

**Comment by stdedos** [comment]
I'd like to see the code used to Pimp, but no file is included in the
repository

**Comment by SchizoDuckie** [comment]
Ah :) switch to the gh-pages branch! :)

https://github.com/SchizoDuckie/PimpMyuTorrent/blob/gh-pages/js/controllers.js#L56
