### ISSUE TITLE
Pro GUI necessity? 

### ISSUE THREAD

**Issue by octopuserectus** [SchizoDuckie/PimpMyuTorrent#6]
I don’t think you should enable it by default, it’s distracting and ugly. 
The flag is:
gui.pro_installed

**Comment by SchizoDuckie** [comment]
That's a matter of opinion, I guess. 15% of 30.000 pimps have turned off the pro_installed after pimping.  (That' s why there is a button that can turn it off after you pimp it)

That means another 85% is perfectly happy with pro.

**Comment by octopuserectus** [comment]
I didn’t notice the redirection back to the pimp page with additional buttons, I’m sorry about bothering you.

**Comment by SchizoDuckie** [comment]
Not a problem :+1:
