### ISSUE TITLE
No Files In Repo (Besides README)

### ISSUE THREAD

**Issue by DerekFoulk** [SchizoDuckie/PimpMyuTorrent#8]
I would really love to see how you did this, but I am unable to view any of the files because all that you've tracked is the README. Any chance we can see the files in the future?

**Comment by SchizoDuckie** [comment]
Please check the gh-pages branch :)

**Comment by DerekFoulk** [comment]
Awesome, thank you much! I love learning little tricks like this. Makes reformatting or setting up new rigs a breeze!
